# world configs 
discrete_action_space: false 
discrete_action_input: false 
discrete_action: false 
world_size: 1
dim_p: 2
dim_c: 4 
num_good_agents: 2
num_adversaries: 4
num_landmarks: 1
num_food: 2
num_forests: 2
# entity configs
agent_pos_init: [uniform, -1, 1]
landmark_pos_init: [uniform, -1, 1]
agent_collide: true 
agent_silence: true  

